name: linux

on:
  - push
  - workflow_dispatch
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: true
      matrix:
        name: ["linux-py39"]
        
        include:
          - name: "linux-py39"
            python-version: "3.9"
            os: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    
    - name: git clone PyDev.Debugger
      run: |
        cd ..
        git clone --depth 1 https://github.com/fabioz/PyDev.Debugger.git
        
    - name: Compile attach to process on Windows
      shell: bash
      run: |
        cd ../PyDev.Debugger/pydevd_attach_to_process/linux_and_mac
        ./compile_linux.sh
        
    - name: Copy files to upload
      shell: bash
      run: |
        cp ../PyDev.Debugger/pydevd_attach_to_process/*.so .
        ls -la
           
        
    - uses: actions/upload-artifact@v2
      with:
        name: linux_binaries
        path: |
          *.so
  armv64_job:
      name: Build and Test for arm64
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1
        - name: Install and Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              arm64v8/ubuntu:20.04 \
              bash -exc 'apt-get update && apt-get -y install python3 python3-pip python3-venv curl git && \
              python3 -m pip install virtualenv && python3 -m venv py38-venv && \
              source py38-venv/bin/activate && \
              
              ls && \
              pwd && \
              uname -m && \
              
              ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && export DEBIAN_FRONTEND=noninteractive && apt-get install -y tzdata && dpkg-reconfigure --frontend noninteractive tzdata && \
              cd .. && \
              git clone --depth 1 https://github.com/bhumikapaharia/PyDev.Debugger.git && \
              ls && \
              pwd && \
              wget https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz && \
              tar -xvf gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz && \
              export PATH=/home/bhumika/toolchain/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu//bin:$PATH
              cd ../PyDev.Debugger/pydevd_attach_to_process/linux_and_mac && \
              ./compile_linux.sh && \
              cp ../PyDev.Debugger/pydevd_attach_to_process/*.so . && \
              ls -la && \
              deactivate'
